name = "InformationDistances"
uuid = "abb756f7-3127-476d-9279-572d0f4d7c25"
authors = ["Simon Schoelly <sischoel@gmail.com> and contributors"]
version = "0.1.0"

[deps]
CodecXz = "ba30903b-d9e8-5048-a5ec-d1f5b0d4b47b"
Distances = "b4f34e82-e78d-54a5-968a-f98e89d6e8f7"
LibDeflate = "9255714d-24a7-4b30-8ea3-d46a97f7e13b"
TranscodingStreams = "3bb67fe8-82b1-5028-8e26-92a6c54297fa"

[compat]
CodecXz = "0.7"
Distances = "0.10"
LibDeflate = "0.1, 0.3"
TranscodingStreams = "0.9.5"
julia = "1.5"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
