name: Export Pluto notebooks
on: workflow_dispatch

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Install Julia
              uses: julia-actions/setup-julia@v1
              with:
                  version: 1.5
            - name: Run Pluto notebooks
              run: julia -e 'using Pkg;
                  env = mktempdir();
                  Pkg.activate(env);
                  Pkg.add([
                  Pkg.PackageSpec(url="https://github.com/fonsp/PlutoUtils.jl", rev="static-export"),
                  Pkg.PackageSpec(url="https://github.com/fonsp/Pluto.jl", rev="8cf1689"),
                  ]);

                  import PlutoUtils;

                  PlutoUtils.Export.github_action(; export_dir=".", offer_binder=false);'
            - name: Deploy to gh-pages
              uses: JamesIves/github-pages-deploy-action@releases/v3
              with:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  BRANCH: gh-pages
                  FOLDER: .
